insert into fortunes (id, text) values (1000, 'People are naturally attracted to you.');
insert into fortunes (id, text) values (1001, 'You learn from your mistakes... You will learn a lot today.');
insert into fortunes (id, text) values (1002, 'If you have something good in your life, don''t let it go!');
insert into fortunes (id, text) values (1003, 'What ever you''re goal is in life, embrace it visualize it, and for it will be yours.');
insert into fortunes (id, text) values (1004, 'Your shoes will make you happy today.');
insert into fortunes (id, text) values (1005, 'You cannot love life until you live the life you love.');
insert into fortunes (id, text) values (1006, 'Be on the lookout for coming events; They cast their shadows beforehand.');
insert into fortunes (id, text) values (1007, 'Land is always on the mind of a flying bird.');
insert into fortunes (id, text) values (1008, 'The man or woman you desire feels the same about you.');
insert into fortunes (id, text) values (1009, 'Meeting adversity well is the source of your strength.');
insert into fortunes (id, text) values (1010, 'A dream you have will come true.');
insert into fortunes (id, text) values (1011, 'Our deeds determine us, as much as we determine our deeds.');
insert into fortunes (id, text) values (1012, 'Never give up. You''re not a failure if you don''t give up.');
insert into fortunes (id, text) values (1013, 'You will become great if you believe in yourself.');
insert into fortunes (id, text) values (1014, 'There is no greater pleasure than seeing your loved ones prosper.');
insert into fortunes (id, text) values (1015, 'You will marry your lover.');
insert into fortunes (id, text) values (1016, 'A very attractive person has a message for you.');
insert into fortunes (id, text) values (1017, 'You already know the answer to the questions lingering inside your head.');
insert into fortunes (id, text) values (1018, 'It is now, and in this world, that we must live.');
insert into fortunes (id, text) values (1019, 'You must try, or hate yourself for not trying.');
insert into fortunes (id, text) values (1020, 'You can make your own happiness.');
insert into fortunes (id, text) values (1021, 'The greatest risk is not taking one.');
insert into fortunes (id, text) values (1022, 'The love of your life is stepping into your planet this summer.');
insert into fortunes (id, text) values (1023, 'Love can last a lifetime, if you want it to.');
insert into fortunes (id, text) values (1024, 'Adversity is the parent of virtue.');
insert into fortunes (id, text) values (1025, 'Serious trouble will bypass you.');
insert into fortunes (id, text) values (1026, 'A short stranger will soon enter your life with blessings to share.');
insert into fortunes (id, text) values (1027, 'Now is the time to try something new.');
insert into fortunes (id, text) values (1028, 'Wealth awaits you very soon.');
insert into fortunes (id, text) values (1029, 'If you feel you are right, stand firmly by your convictions.');
insert into fortunes (id, text) values (1030, 'If winter comes, can spring be far behind?');
insert into fortunes (id, text) values (1031, 'Keep your eye out for someone special.');
insert into fortunes (id, text) values (1032, 'You are very talented in many ways.');
insert into fortunes (id, text) values (1033, 'A stranger, is a friend you have not spoken to yet.');
insert into fortunes (id, text) values (1034, 'A new voyage will fill your life with untold memories.');
insert into fortunes (id, text) values (1035, 'You will travel to many exotic places in your lifetime.');
insert into fortunes (id, text) values (1036, 'Your ability for accomplishment will follow with success.');
insert into fortunes (id, text) values (1037, 'Nothing astonishes men so much as common sense and plain dealing.');
insert into fortunes (id, text) values (1038, 'Its amazing how much good you can do if you dont care who gets the credit.');
insert into fortunes (id, text) values (1039, 'Everyone agrees. You are the best.');
insert into fortunes (id, text) values (1040, 'LIFE CONSIST NOT IN HOLDING GOOD CARDS, BUT IN PLAYING THOSE YOU HOLD WELL.');
insert into fortunes (id, text) values (1041, 'Jealousy doesn''t open doors, it closes them!');
insert into fortunes (id, text) values (1042, 'It''s better to be alone sometimes.');
insert into fortunes (id, text) values (1043, 'When fear hurts you, conquer it and defeat it!');
insert into fortunes (id, text) values (1044, 'Let the deeds speak.');
insert into fortunes (id, text) values (1045, 'You will be called in to fulfill a position of high honor and responsibility.');
insert into fortunes (id, text) values (1046, 'The man on the top of the mountain did not fall there.');
insert into fortunes (id, text) values (1047, 'You will conquer obstacles to achieve success.');
insert into fortunes (id, text) values (1048, 'Joys are often the shadows, cast by sorrows.');
insert into fortunes (id, text) values (1049, 'Fortune favors the brave.');
